/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateProjectInput {
  'kw' : [] | [number],
  'region' : string,
  'customerName' : string,
  'cashAmount2' : [] | [number],
  'financeDate1' : [] | [string],
  'financeDate2' : [] | [string],
  'gstFillingMonth' : [] | [string],
  'employeeName' : [] | [string],
  'employeeType' : string,
  'nextStage' : [] | [string],
  'lastPaymentDate' : [] | [string],
  'slNo' : bigint,
  'bookingAmount' : [] | [number],
  'freelancerName' : [] | [string],
  'invoiceNo' : [] | [string],
  'deliveryDate' : [] | [string],
  'ewayBillNo' : [] | [string],
  'financeAmount1' : [] | [number],
  'financeAmount2' : [] | [number],
  'netMeteringDate' : [] | [string],
  'gstAmount' : [] | [number],
  'materialPurchaseDate' : [] | [string],
  'district' : [] | [string],
  'bookingAgreementDate' : [] | [string],
  'bookingAmountDate' : [] | [string],
  'address' : [] | [string],
  'subsidyDisbursed' : [] | [number],
  'leadSource' : string,
  'signAgreement' : [] | [boolean],
  'projectStatus' : ProjectStatus,
  'salePrice' : [] | [number],
  'consumerAcNo' : [] | [string],
  'phoneNumber' : [] | [string],
  'currentStage' : [] | [string],
  'pendingAmount' : [] | [number],
  'cashAmount2Date' : [] | [string],
  'remarks' : [] | [string],
  'installationDate' : [] | [string],
  'digitalApprovedLetter' : [] | [boolean],
}
export type ProjectStatus = { 'ONGOING' : null } |
  { 'OPEN' : null } |
  { 'REJECT' : null } |
  { 'CLOSED' : null };
export interface SolarProject {
  'id' : string,
  'kw' : [] | [number],
  'region' : string,
  'customerName' : string,
  'cashAmount2' : [] | [number],
  'financeDate1' : [] | [string],
  'financeDate2' : [] | [string],
  'gstFillingMonth' : [] | [string],
  'employeeName' : [] | [string],
  'employeeType' : string,
  'nextStage' : [] | [string],
  'lastPaymentDate' : [] | [string],
  'slNo' : bigint,
  'bookingAmount' : [] | [number],
  'freelancerName' : [] | [string],
  'invoiceNo' : [] | [string],
  'deliveryDate' : [] | [string],
  'ewayBillNo' : [] | [string],
  'financeAmount1' : [] | [number],
  'financeAmount2' : [] | [number],
  'netMeteringDate' : [] | [string],
  'gstAmount' : [] | [number],
  'materialPurchaseDate' : [] | [string],
  'district' : [] | [string],
  'bookingAgreementDate' : [] | [string],
  'bookingAmountDate' : [] | [string],
  'address' : [] | [string],
  'subsidyDisbursed' : [] | [number],
  'leadSource' : string,
  'signAgreement' : [] | [boolean],
  'projectStatus' : ProjectStatus,
  'salePrice' : [] | [number],
  'consumerAcNo' : [] | [string],
  'phoneNumber' : [] | [string],
  'currentStage' : [] | [string],
  'pendingAmount' : [] | [number],
  'cashAmount2Date' : [] | [string],
  'remarks' : [] | [string],
  'installationDate' : [] | [string],
  'digitalApprovedLetter' : [] | [boolean],
}
export interface UpdateProjectInput {
  'id' : string,
  'kw' : [] | [number],
  'region' : string,
  'customerName' : string,
  'cashAmount2' : [] | [number],
  'financeDate1' : [] | [string],
  'financeDate2' : [] | [string],
  'gstFillingMonth' : [] | [string],
  'employeeName' : [] | [string],
  'employeeType' : string,
  'nextStage' : [] | [string],
  'lastPaymentDate' : [] | [string],
  'slNo' : bigint,
  'bookingAmount' : [] | [number],
  'freelancerName' : [] | [string],
  'invoiceNo' : [] | [string],
  'deliveryDate' : [] | [string],
  'ewayBillNo' : [] | [string],
  'financeAmount1' : [] | [number],
  'financeAmount2' : [] | [number],
  'netMeteringDate' : [] | [string],
  'gstAmount' : [] | [number],
  'materialPurchaseDate' : [] | [string],
  'district' : [] | [string],
  'bookingAgreementDate' : [] | [string],
  'bookingAmountDate' : [] | [string],
  'address' : [] | [string],
  'subsidyDisbursed' : [] | [number],
  'leadSource' : string,
  'signAgreement' : [] | [boolean],
  'projectStatus' : ProjectStatus,
  'salePrice' : [] | [number],
  'consumerAcNo' : [] | [string],
  'phoneNumber' : [] | [string],
  'currentStage' : [] | [string],
  'pendingAmount' : [] | [number],
  'cashAmount2Date' : [] | [string],
  'remarks' : [] | [string],
  'installationDate' : [] | [string],
  'digitalApprovedLetter' : [] | [boolean],
}
export interface UserInfo { 'accessLevel' : string, 'username' : string }
export interface UserSession {
  'accessLevel' : string,
  'token' : string,
  'username' : string,
}
export interface _SERVICE {
  'createProject' : ActorMethod<[CreateProjectInput], SolarProject>,
  'createUser' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteProject' : ActorMethod<[string], boolean>,
  'deleteUser' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getAllProjects' : ActorMethod<[], Array<SolarProject>>,
  'getProject' : ActorMethod<[string], [] | [SolarProject]>,
  'getProjectsByRegion' : ActorMethod<[string], Array<SolarProject>>,
  'getProjectsByStatus' : ActorMethod<[ProjectStatus], Array<SolarProject>>,
  'listUsers' : ActorMethod<
    [string],
    { 'ok' : Array<UserInfo> } |
      { 'err' : string }
  >,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : UserSession } |
      { 'err' : string }
  >,
  'updateProject' : ActorMethod<[UpdateProjectInput], [] | [SolarProject]>,
  'validateSession' : ActorMethod<
    [string],
    { 'ok' : UserInfo } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];