/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateProjectInput {
    kw?: number;
    region: string;
    customerName: string;
    cashAmount2?: number;
    financeDate1?: string;
    financeDate2?: string;
    gstFillingMonth?: string;
    employeeName?: string;
    employeeType: string;
    nextStage?: string;
    lastPaymentDate?: string;
    slNo: bigint;
    bookingAmount?: number;
    freelancerName?: string;
    invoiceNo?: string;
    deliveryDate?: string;
    ewayBillNo?: string;
    financeAmount1?: number;
    financeAmount2?: number;
    netMeteringDate?: string;
    gstAmount?: number;
    materialPurchaseDate?: string;
    district?: string;
    bookingAgreementDate?: string;
    bookingAmountDate?: string;
    address?: string;
    subsidyDisbursed?: number;
    leadSource: string;
    signAgreement?: boolean;
    projectStatus: ProjectStatus;
    salePrice?: number;
    consumerAcNo?: string;
    phoneNumber?: string;
    currentStage?: string;
    pendingAmount?: number;
    cashAmount2Date?: string;
    remarks?: string;
    installationDate?: string;
    digitalApprovedLetter?: boolean;
}
export interface UpdateProjectInput {
    id: string;
    kw?: number;
    region: string;
    customerName: string;
    cashAmount2?: number;
    financeDate1?: string;
    financeDate2?: string;
    gstFillingMonth?: string;
    employeeName?: string;
    employeeType: string;
    nextStage?: string;
    lastPaymentDate?: string;
    slNo: bigint;
    bookingAmount?: number;
    freelancerName?: string;
    invoiceNo?: string;
    deliveryDate?: string;
    ewayBillNo?: string;
    financeAmount1?: number;
    financeAmount2?: number;
    netMeteringDate?: string;
    gstAmount?: number;
    materialPurchaseDate?: string;
    district?: string;
    bookingAgreementDate?: string;
    bookingAmountDate?: string;
    address?: string;
    subsidyDisbursed?: number;
    leadSource: string;
    signAgreement?: boolean;
    projectStatus: ProjectStatus;
    salePrice?: number;
    consumerAcNo?: string;
    phoneNumber?: string;
    currentStage?: string;
    pendingAmount?: number;
    cashAmount2Date?: string;
    remarks?: string;
    installationDate?: string;
    digitalApprovedLetter?: boolean;
}
export interface UserSession {
    accessLevel: string;
    token: string;
    username: string;
}
export interface UserInfo {
    accessLevel: string;
    username: string;
}
export interface SolarProject {
    id: string;
    kw?: number;
    region: string;
    customerName: string;
    cashAmount2?: number;
    financeDate1?: string;
    financeDate2?: string;
    gstFillingMonth?: string;
    employeeName?: string;
    employeeType: string;
    nextStage?: string;
    lastPaymentDate?: string;
    slNo: bigint;
    bookingAmount?: number;
    freelancerName?: string;
    invoiceNo?: string;
    deliveryDate?: string;
    ewayBillNo?: string;
    financeAmount1?: number;
    financeAmount2?: number;
    netMeteringDate?: string;
    gstAmount?: number;
    materialPurchaseDate?: string;
    district?: string;
    bookingAgreementDate?: string;
    bookingAmountDate?: string;
    address?: string;
    subsidyDisbursed?: number;
    leadSource: string;
    signAgreement?: boolean;
    projectStatus: ProjectStatus;
    salePrice?: number;
    consumerAcNo?: string;
    phoneNumber?: string;
    currentStage?: string;
    pendingAmount?: number;
    cashAmount2Date?: string;
    remarks?: string;
    installationDate?: string;
    digitalApprovedLetter?: boolean;
}
export enum ProjectStatus {
    ONGOING = "ONGOING",
    OPEN = "OPEN",
    REJECT = "REJECT",
    CLOSED = "CLOSED"
}
export interface backendInterface {
    createProject(input: CreateProjectInput): Promise<SolarProject>;
    createUser(callerToken: string, username: string, password: string, accessLevel: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteProject(id: string): Promise<boolean>;
    deleteUser(callerToken: string, username: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllProjects(): Promise<Array<SolarProject>>;
    getProject(id: string): Promise<SolarProject | null>;
    getProjectsByRegion(region: string): Promise<Array<SolarProject>>;
    getProjectsByStatus(status: ProjectStatus): Promise<Array<SolarProject>>;
    listUsers(callerToken: string): Promise<{
        __kind__: "ok";
        ok: Array<UserInfo>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    login(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: UserSession;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateProject(input: UpdateProjectInput): Promise<SolarProject | null>;
    validateSession(token: string): Promise<{
        __kind__: "ok";
        ok: UserInfo;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { CreateProjectInput as _CreateProjectInput, ProjectStatus as _ProjectStatus, SolarProject as _SolarProject, UpdateProjectInput as _UpdateProjectInput, UserInfo as _UserInfo, UserSession as _UserSession } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createProject(arg0: CreateProjectInput): Promise<SolarProject> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_CreateProjectInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SolarProject_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_CreateProjectInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SolarProject_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2, arg3);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2, arg3);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProject(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0, arg1);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0, arg1);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjects(): Promise<Array<SolarProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: string): Promise<SolarProject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectsByRegion(arg0: string): Promise<Array<SolarProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByRegion(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByRegion(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectsByStatus(arg0: ProjectStatus): Promise<Array<SolarProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByStatus(to_candid_ProjectStatus_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByStatus(to_candid_ProjectStatus_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<UserInfo>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers(arg0);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers(arg0);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: UserSession;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: UpdateProjectInput): Promise<SolarProject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(to_candid_UpdateProjectInput_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(to_candid_UpdateProjectInput_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateSession(arg0: string): Promise<{
        __kind__: "ok";
        ok: UserInfo;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ProjectStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SolarProject_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SolarProject): SolarProject {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SolarProject]): SolarProject | null {
    return value.length === 0 ? null : from_candid_SolarProject_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    kw: [] | [number];
    region: string;
    customerName: string;
    cashAmount2: [] | [number];
    financeDate1: [] | [string];
    financeDate2: [] | [string];
    gstFillingMonth: [] | [string];
    employeeName: [] | [string];
    employeeType: string;
    nextStage: [] | [string];
    lastPaymentDate: [] | [string];
    slNo: bigint;
    bookingAmount: [] | [number];
    freelancerName: [] | [string];
    invoiceNo: [] | [string];
    deliveryDate: [] | [string];
    ewayBillNo: [] | [string];
    financeAmount1: [] | [number];
    financeAmount2: [] | [number];
    netMeteringDate: [] | [string];
    gstAmount: [] | [number];
    materialPurchaseDate: [] | [string];
    district: [] | [string];
    bookingAgreementDate: [] | [string];
    bookingAmountDate: [] | [string];
    address: [] | [string];
    subsidyDisbursed: [] | [number];
    leadSource: string;
    signAgreement: [] | [boolean];
    projectStatus: _ProjectStatus;
    salePrice: [] | [number];
    consumerAcNo: [] | [string];
    phoneNumber: [] | [string];
    currentStage: [] | [string];
    pendingAmount: [] | [number];
    cashAmount2Date: [] | [string];
    remarks: [] | [string];
    installationDate: [] | [string];
    digitalApprovedLetter: [] | [boolean];
}): {
    id: string;
    kw?: number;
    region: string;
    customerName: string;
    cashAmount2?: number;
    financeDate1?: string;
    financeDate2?: string;
    gstFillingMonth?: string;
    employeeName?: string;
    employeeType: string;
    nextStage?: string;
    lastPaymentDate?: string;
    slNo: bigint;
    bookingAmount?: number;
    freelancerName?: string;
    invoiceNo?: string;
    deliveryDate?: string;
    ewayBillNo?: string;
    financeAmount1?: number;
    financeAmount2?: number;
    netMeteringDate?: string;
    gstAmount?: number;
    materialPurchaseDate?: string;
    district?: string;
    bookingAgreementDate?: string;
    bookingAmountDate?: string;
    address?: string;
    subsidyDisbursed?: number;
    leadSource: string;
    signAgreement?: boolean;
    projectStatus: ProjectStatus;
    salePrice?: number;
    consumerAcNo?: string;
    phoneNumber?: string;
    currentStage?: string;
    pendingAmount?: number;
    cashAmount2Date?: string;
    remarks?: string;
    installationDate?: string;
    digitalApprovedLetter?: boolean;
} {
    return {
        id: value.id,
        kw: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.kw)),
        region: value.region,
        customerName: value.customerName,
        cashAmount2: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.cashAmount2)),
        financeDate1: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.financeDate1)),
        financeDate2: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.financeDate2)),
        gstFillingMonth: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.gstFillingMonth)),
        employeeName: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.employeeName)),
        employeeType: value.employeeType,
        nextStage: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.nextStage)),
        lastPaymentDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.lastPaymentDate)),
        slNo: value.slNo,
        bookingAmount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.bookingAmount)),
        freelancerName: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.freelancerName)),
        invoiceNo: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.invoiceNo)),
        deliveryDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.deliveryDate)),
        ewayBillNo: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.ewayBillNo)),
        financeAmount1: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.financeAmount1)),
        financeAmount2: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.financeAmount2)),
        netMeteringDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.netMeteringDate)),
        gstAmount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.gstAmount)),
        materialPurchaseDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.materialPurchaseDate)),
        district: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.district)),
        bookingAgreementDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.bookingAgreementDate)),
        bookingAmountDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.bookingAmountDate)),
        address: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.address)),
        subsidyDisbursed: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.subsidyDisbursed)),
        leadSource: value.leadSource,
        signAgreement: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.signAgreement)),
        projectStatus: from_candid_ProjectStatus_n10(_uploadFile, _downloadFile, value.projectStatus),
        salePrice: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.salePrice)),
        consumerAcNo: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.consumerAcNo)),
        phoneNumber: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.phoneNumber)),
        currentStage: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.currentStage)),
        pendingAmount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.pendingAmount)),
        cashAmount2Date: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.cashAmount2Date)),
        remarks: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.remarks)),
        installationDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.installationDate)),
        digitalApprovedLetter: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.digitalApprovedLetter))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ONGOING: null;
} | {
    OPEN: null;
} | {
    REJECT: null;
} | {
    CLOSED: null;
}): ProjectStatus {
    return "ONGOING" in value ? ProjectStatus.ONGOING : "OPEN" in value ? ProjectStatus.OPEN : "REJECT" in value ? ProjectStatus.REJECT : "CLOSED" in value ? ProjectStatus.CLOSED : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_UserInfo>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<UserInfo>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserSession;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserSession;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserInfo;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserInfo;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SolarProject>): Array<SolarProject> {
    return value.map((x)=>from_candid_SolarProject_n5(_uploadFile, _downloadFile, x));
}
function to_candid_CreateProjectInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProjectInput): _CreateProjectInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProjectInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProjectInput): _UpdateProjectInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    kw?: number;
    region: string;
    customerName: string;
    cashAmount2?: number;
    financeDate1?: string;
    financeDate2?: string;
    gstFillingMonth?: string;
    employeeName?: string;
    employeeType: string;
    nextStage?: string;
    lastPaymentDate?: string;
    slNo: bigint;
    bookingAmount?: number;
    freelancerName?: string;
    invoiceNo?: string;
    deliveryDate?: string;
    ewayBillNo?: string;
    financeAmount1?: number;
    financeAmount2?: number;
    netMeteringDate?: string;
    gstAmount?: number;
    materialPurchaseDate?: string;
    district?: string;
    bookingAgreementDate?: string;
    bookingAmountDate?: string;
    address?: string;
    subsidyDisbursed?: number;
    leadSource: string;
    signAgreement?: boolean;
    projectStatus: ProjectStatus;
    salePrice?: number;
    consumerAcNo?: string;
    phoneNumber?: string;
    currentStage?: string;
    pendingAmount?: number;
    cashAmount2Date?: string;
    remarks?: string;
    installationDate?: string;
    digitalApprovedLetter?: boolean;
}): {
    id: string;
    kw: [] | [number];
    region: string;
    customerName: string;
    cashAmount2: [] | [number];
    financeDate1: [] | [string];
    financeDate2: [] | [string];
    gstFillingMonth: [] | [string];
    employeeName: [] | [string];
    employeeType: string;
    nextStage: [] | [string];
    lastPaymentDate: [] | [string];
    slNo: bigint;
    bookingAmount: [] | [number];
    freelancerName: [] | [string];
    invoiceNo: [] | [string];
    deliveryDate: [] | [string];
    ewayBillNo: [] | [string];
    financeAmount1: [] | [number];
    financeAmount2: [] | [number];
    netMeteringDate: [] | [string];
    gstAmount: [] | [number];
    materialPurchaseDate: [] | [string];
    district: [] | [string];
    bookingAgreementDate: [] | [string];
    bookingAmountDate: [] | [string];
    address: [] | [string];
    subsidyDisbursed: [] | [number];
    leadSource: string;
    signAgreement: [] | [boolean];
    projectStatus: _ProjectStatus;
    salePrice: [] | [number];
    consumerAcNo: [] | [string];
    phoneNumber: [] | [string];
    currentStage: [] | [string];
    pendingAmount: [] | [number];
    cashAmount2Date: [] | [string];
    remarks: [] | [string];
    installationDate: [] | [string];
    digitalApprovedLetter: [] | [boolean];
} {
    return {
        id: value.id,
        kw: value.kw ? candid_some(value.kw) : candid_none(),
        region: value.region,
        customerName: value.customerName,
        cashAmount2: value.cashAmount2 ? candid_some(value.cashAmount2) : candid_none(),
        financeDate1: value.financeDate1 ? candid_some(value.financeDate1) : candid_none(),
        financeDate2: value.financeDate2 ? candid_some(value.financeDate2) : candid_none(),
        gstFillingMonth: value.gstFillingMonth ? candid_some(value.gstFillingMonth) : candid_none(),
        employeeName: value.employeeName ? candid_some(value.employeeName) : candid_none(),
        employeeType: value.employeeType,
        nextStage: value.nextStage ? candid_some(value.nextStage) : candid_none(),
        lastPaymentDate: value.lastPaymentDate ? candid_some(value.lastPaymentDate) : candid_none(),
        slNo: value.slNo,
        bookingAmount: value.bookingAmount ? candid_some(value.bookingAmount) : candid_none(),
        freelancerName: value.freelancerName ? candid_some(value.freelancerName) : candid_none(),
        invoiceNo: value.invoiceNo ? candid_some(value.invoiceNo) : candid_none(),
        deliveryDate: value.deliveryDate ? candid_some(value.deliveryDate) : candid_none(),
        ewayBillNo: value.ewayBillNo ? candid_some(value.ewayBillNo) : candid_none(),
        financeAmount1: value.financeAmount1 ? candid_some(value.financeAmount1) : candid_none(),
        financeAmount2: value.financeAmount2 ? candid_some(value.financeAmount2) : candid_none(),
        netMeteringDate: value.netMeteringDate ? candid_some(value.netMeteringDate) : candid_none(),
        gstAmount: value.gstAmount ? candid_some(value.gstAmount) : candid_none(),
        materialPurchaseDate: value.materialPurchaseDate ? candid_some(value.materialPurchaseDate) : candid_none(),
        district: value.district ? candid_some(value.district) : candid_none(),
        bookingAgreementDate: value.bookingAgreementDate ? candid_some(value.bookingAgreementDate) : candid_none(),
        bookingAmountDate: value.bookingAmountDate ? candid_some(value.bookingAmountDate) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        subsidyDisbursed: value.subsidyDisbursed ? candid_some(value.subsidyDisbursed) : candid_none(),
        leadSource: value.leadSource,
        signAgreement: value.signAgreement ? candid_some(value.signAgreement) : candid_none(),
        projectStatus: to_candid_ProjectStatus_n3(_uploadFile, _downloadFile, value.projectStatus),
        salePrice: value.salePrice ? candid_some(value.salePrice) : candid_none(),
        consumerAcNo: value.consumerAcNo ? candid_some(value.consumerAcNo) : candid_none(),
        phoneNumber: value.phoneNumber ? candid_some(value.phoneNumber) : candid_none(),
        currentStage: value.currentStage ? candid_some(value.currentStage) : candid_none(),
        pendingAmount: value.pendingAmount ? candid_some(value.pendingAmount) : candid_none(),
        cashAmount2Date: value.cashAmount2Date ? candid_some(value.cashAmount2Date) : candid_none(),
        remarks: value.remarks ? candid_some(value.remarks) : candid_none(),
        installationDate: value.installationDate ? candid_some(value.installationDate) : candid_none(),
        digitalApprovedLetter: value.digitalApprovedLetter ? candid_some(value.digitalApprovedLetter) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kw?: number;
    region: string;
    customerName: string;
    cashAmount2?: number;
    financeDate1?: string;
    financeDate2?: string;
    gstFillingMonth?: string;
    employeeName?: string;
    employeeType: string;
    nextStage?: string;
    lastPaymentDate?: string;
    slNo: bigint;
    bookingAmount?: number;
    freelancerName?: string;
    invoiceNo?: string;
    deliveryDate?: string;
    ewayBillNo?: string;
    financeAmount1?: number;
    financeAmount2?: number;
    netMeteringDate?: string;
    gstAmount?: number;
    materialPurchaseDate?: string;
    district?: string;
    bookingAgreementDate?: string;
    bookingAmountDate?: string;
    address?: string;
    subsidyDisbursed?: number;
    leadSource: string;
    signAgreement?: boolean;
    projectStatus: ProjectStatus;
    salePrice?: number;
    consumerAcNo?: string;
    phoneNumber?: string;
    currentStage?: string;
    pendingAmount?: number;
    cashAmount2Date?: string;
    remarks?: string;
    installationDate?: string;
    digitalApprovedLetter?: boolean;
}): {
    kw: [] | [number];
    region: string;
    customerName: string;
    cashAmount2: [] | [number];
    financeDate1: [] | [string];
    financeDate2: [] | [string];
    gstFillingMonth: [] | [string];
    employeeName: [] | [string];
    employeeType: string;
    nextStage: [] | [string];
    lastPaymentDate: [] | [string];
    slNo: bigint;
    bookingAmount: [] | [number];
    freelancerName: [] | [string];
    invoiceNo: [] | [string];
    deliveryDate: [] | [string];
    ewayBillNo: [] | [string];
    financeAmount1: [] | [number];
    financeAmount2: [] | [number];
    netMeteringDate: [] | [string];
    gstAmount: [] | [number];
    materialPurchaseDate: [] | [string];
    district: [] | [string];
    bookingAgreementDate: [] | [string];
    bookingAmountDate: [] | [string];
    address: [] | [string];
    subsidyDisbursed: [] | [number];
    leadSource: string;
    signAgreement: [] | [boolean];
    projectStatus: _ProjectStatus;
    salePrice: [] | [number];
    consumerAcNo: [] | [string];
    phoneNumber: [] | [string];
    currentStage: [] | [string];
    pendingAmount: [] | [number];
    cashAmount2Date: [] | [string];
    remarks: [] | [string];
    installationDate: [] | [string];
    digitalApprovedLetter: [] | [boolean];
} {
    return {
        kw: value.kw ? candid_some(value.kw) : candid_none(),
        region: value.region,
        customerName: value.customerName,
        cashAmount2: value.cashAmount2 ? candid_some(value.cashAmount2) : candid_none(),
        financeDate1: value.financeDate1 ? candid_some(value.financeDate1) : candid_none(),
        financeDate2: value.financeDate2 ? candid_some(value.financeDate2) : candid_none(),
        gstFillingMonth: value.gstFillingMonth ? candid_some(value.gstFillingMonth) : candid_none(),
        employeeName: value.employeeName ? candid_some(value.employeeName) : candid_none(),
        employeeType: value.employeeType,
        nextStage: value.nextStage ? candid_some(value.nextStage) : candid_none(),
        lastPaymentDate: value.lastPaymentDate ? candid_some(value.lastPaymentDate) : candid_none(),
        slNo: value.slNo,
        bookingAmount: value.bookingAmount ? candid_some(value.bookingAmount) : candid_none(),
        freelancerName: value.freelancerName ? candid_some(value.freelancerName) : candid_none(),
        invoiceNo: value.invoiceNo ? candid_some(value.invoiceNo) : candid_none(),
        deliveryDate: value.deliveryDate ? candid_some(value.deliveryDate) : candid_none(),
        ewayBillNo: value.ewayBillNo ? candid_some(value.ewayBillNo) : candid_none(),
        financeAmount1: value.financeAmount1 ? candid_some(value.financeAmount1) : candid_none(),
        financeAmount2: value.financeAmount2 ? candid_some(value.financeAmount2) : candid_none(),
        netMeteringDate: value.netMeteringDate ? candid_some(value.netMeteringDate) : candid_none(),
        gstAmount: value.gstAmount ? candid_some(value.gstAmount) : candid_none(),
        materialPurchaseDate: value.materialPurchaseDate ? candid_some(value.materialPurchaseDate) : candid_none(),
        district: value.district ? candid_some(value.district) : candid_none(),
        bookingAgreementDate: value.bookingAgreementDate ? candid_some(value.bookingAgreementDate) : candid_none(),
        bookingAmountDate: value.bookingAmountDate ? candid_some(value.bookingAmountDate) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        subsidyDisbursed: value.subsidyDisbursed ? candid_some(value.subsidyDisbursed) : candid_none(),
        leadSource: value.leadSource,
        signAgreement: value.signAgreement ? candid_some(value.signAgreement) : candid_none(),
        projectStatus: to_candid_ProjectStatus_n3(_uploadFile, _downloadFile, value.projectStatus),
        salePrice: value.salePrice ? candid_some(value.salePrice) : candid_none(),
        consumerAcNo: value.consumerAcNo ? candid_some(value.consumerAcNo) : candid_none(),
        phoneNumber: value.phoneNumber ? candid_some(value.phoneNumber) : candid_none(),
        currentStage: value.currentStage ? candid_some(value.currentStage) : candid_none(),
        pendingAmount: value.pendingAmount ? candid_some(value.pendingAmount) : candid_none(),
        cashAmount2Date: value.cashAmount2Date ? candid_some(value.cashAmount2Date) : candid_none(),
        remarks: value.remarks ? candid_some(value.remarks) : candid_none(),
        installationDate: value.installationDate ? candid_some(value.installationDate) : candid_none(),
        digitalApprovedLetter: value.digitalApprovedLetter ? candid_some(value.digitalApprovedLetter) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    ONGOING: null;
} | {
    OPEN: null;
} | {
    REJECT: null;
} | {
    CLOSED: null;
} {
    return value == ProjectStatus.ONGOING ? {
        ONGOING: null
    } : value == ProjectStatus.OPEN ? {
        OPEN: null
    } : value == ProjectStatus.REJECT ? {
        REJECT: null
    } : value == ProjectStatus.CLOSED ? {
        CLOSED: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
